apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config
  namespace: vote
data:
  filebeat.yml: |
    filebeat.inputs:
    - type: log
      paths:
        - /var/log/gunicorn_access.log
    output.elasticsearch:
      hosts: ["http://192.168.1.112:9200"]
      username: "elastic"
      password: "asus1650"
      index: vote-%{+yyyy.MM.dd}
    setup.template:
      name: 'vote'
      pattern: 'vote-*'