apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: vote-service
  namespace: vote
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: vote-service
  endpoints:
  - port: web
