apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  namespace: python-web
  name: myapp
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: python-web
  endpoints:
    - port: http-metrics
      path: /metrics
