apiVersion: v1
kind: Service
metadata:
  name: my-service
  namespace: python-web
spec:
  type: NodePort
  selector:
    app: python-web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
