---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: targets
  namespace: monitoring
  labels:
    prometheus: prometheus
    release: prometheus
spec:
  groups:
    - name: targets
      rules:
        - alert: PrometheusTargetMissing
          expr: up == 1
          for: 0m
          labels:
            severity: warning
            environment: stage
          annotations:
            summary: Prometheus target missing (instance {{ $labels.instance }})
            description: "A Prometheus target has disappeared. An exporter might be crashed.\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
