apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: main
  labels:
    prometheus: prometheus
  namespace: monitoring
spec:
  alerting:
    alertmanagers:
    - name: alertmanager-operated
      port: web
  logLevel: info
  logFormat: logfmt
  retention: 7d
  scrapeInterval: 15s
  replicas: 1
  serviceAccountName: prometheus
  podMonitorNamespaceSelector:
    matchLabels:
      namespace: stage
  podMonitorSelector:
    matchLabels:
      team: frontend
  serviceMonitorNamespaceSelector: {}
  serviceMonitorSelector:
    matchExpressions:
    - key: release
      operator: Exists
  ruleNamespaceSelector: {}
  ruleSelector:
    matchExpressions:
    - key: release
      operator: Exists
