apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-vote-deployment
spec:
  scaleTargetRef:
    kind: Deployment
    name: vote-deployment
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 80

