- name: Ensure Directory Exists
  file:
    path: /opt/{{ alertmanager_container_name }}
    state: directory
    mode: '0755'

- name: Render configuration file from template
  copy:
    src: "alertmanager.yaml"
    dest: "/opt/{{ alertmanager_container_name }}"
    mode: "0644"

- name: Generate docker-compose.yaml from template
  template:
    src: "docker-compose.yaml.j2"
    dest: "/opt/{{ alertmanager_container_name }}/docker-compose.yaml"

- name: Copy Template For Slack
  copy:
    src: "slack.tmpl"
    dest: "/opt/{{ alertmanager_container_name }}"

- name: Run Docker Compose
  community.docker.docker_compose_v2:
    project_src: "/opt/{{ alertmanager_container_name }}"
    state: present

- name: Down Docker Compose
  community.docker.docker_compose_v2:
    project_src: "/opt/{{ alertmanager_container_name }}"
    state: absent
  tags:
    - down
