apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-worker-deployment
spec:
  scaleTargetRef:
    kind: Deployment
    name: worker-deployment
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 80

