apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: postgres-db
  labels:
    app: postgres
spec:
  ports:
  - name: postgres
    port: 5432
  clusterIP: None
  selector:
    app: postgres

