apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql
  namespace: mysql-db
  labels:
    app: mysql
    app.kubernetes.io/name: mysql
data:
  primary.cnf: |
    [mysqld]
    log-bin    
  replica.cnf: |
    [mysqld]
    super-read-only    


