version: "3.8"

services:
  db:
    image: mysql:8
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    build: .
    container_name: flask_app
    restart: always
    depends_on:
      - db
    environment:
            DATABASE_URL: "mysql+pymysql://myuser:mypassword@db:3306/mydatabase"
    ports:
      - "5000:5000"
    command: ["python", "app.py"]

volumes:
  mysql_data:

