apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-python-api-deployment
spec:
  scaleTargetRef:
    kind: Deployment
    name: python-api-deployment
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 80

