- hosts: all
  name: Install Requirments All Node
  become: yes
  roles:
  - role: filebeat
    #- role: nexus
    #- role: nexus

    #- hosts: group1
    # name: Install On Group1
    #become: yes
    #roles: 
    #- role: zabbix-agent 
    #- role: requirment
    #- role: elastic
    # - role: kibana
    #- role: elastic

    #- hosts: group1
    #name: install On Group2
    #become: yes
    #roles:
    #- role: sonarqube
    #- role: nexus
    #- role: defectdojo

    #- hosts: group2
    #name: install On Group3
    #become: yes
    #roles:
    #- role: elastic
    #- role: kibana
    #- role: logstash
